defaults: &defaults
  adapter: mysql2
  encoding: utf8mb4
  username: root
  password: 
  host: 127.0.0.1
  port: 3306

development:
  <<: *defaults
  database: <%= XBCampus_development

test:
  <<: *defaults
  database: XBCampus_test

production:
  adapter: postgresql
  database: XBCampus_production


